user:
  max_length_name: 32
  min_length_password: 6
course:
  max_length_name: 32
  max_length_content: 5000
subject:
  max_length_name: 32
  max_length_details: 1024
task:
  max_length_title: 128
  max_length_content: 10000
per_page: 16
cols: 4
